### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by peternann** [jovotech/jovo-framework#35] opened 2017-11-01 12:42 UTC
Just installed jovo on Linux.
Get the error in subject line on any attempt to run 'jovo'.
Looks like Windows format line endings (CR-LF) in jovo.js

Removing the CR from the #! line is enough to get this ship underway...
Wish me calm seas ahead...

**Comment by jankoenig** [comment] 2017-11-01 16:23
Thanks! Will look into this :) And glad you got it to work. Please let us know if you run into additional problems

**Comment by jankoenig** [comment] 2017-11-02 22:50
Hi @peternann, we found the bug and pushed the new version to npm. Can you update it with `npm update -g jovo-cli` and try again? Thanks!

**Comment by peternann** [comment] 2017-11-02 22:54
Thanks Jan.

Great framework by the way.
I heard your chat on VoiceBot.ai and like your style.


We have been developing something highly similar, (in fact almost
identical!), but in the next few weeks we may switch over to Jovo and join
forces with you...

Stay tuned....

**Comment by jankoenig** [comment] 2017-11-02 22:59
Very cool, thanks a lot! 
Would love to chat @peternann. Would you mind sending me an email to jan@jovo.tech so we can talk about potential ways to work together :) Would love to learn more about what you're doing

**Comment by pirvulescu** [comment] 2018-12-21 16:36
Hello, It looks like the problem is back again. I used macOS Mojave10.14.2

**Comment by pirvulescu** [comment] 2018-12-21 16:45
After I converted jovo-cli/dist/index.js to unix format I got this error:

`jovo
/usr/local/lib/node_modules/jovo-cli/node_modules/jovo-cli-core/dist/src/Project.js:27
    async init(frameworkVersion) {
          ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/jovo-cli/node_modules/jovo-cli-core/dist/src/index.js:8:10)
    at Module._compile (module.js:541:32)
`

**Comment by jankoenig** [comment] 2018-12-22 10:36
Resolved in `2.0.3`

**Comment by pirvulescu** [comment] 2018-12-22 14:55
Thanks Jan for the fast response. Unfortunately, I have the same error received after I converted the index.js file to unix format:

jovo -V
/usr/local/lib/node_modules/jovo-cli/node_modules/jovo-cli-core/dist/src/Project.js:27
    async init(frameworkVersion) {
          ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/jovo-cli/node_modules/jovo-cli-core/dist/src/index.js:8:10)
    at Module._compile (module.js:541:32)

**Comment by jankoenig** [comment] 2018-12-22 15:07
Hi Dan, sorry for closing this issue too soon. We had a similar problem in our Slack community where someone reported this to be resolved now.

Which version of Node do you have installed, could you try `node -v`?

**Comment by pirvulescu** [comment] 2018-12-22 16:15
Hi Jan,
Sorry, but I cannot respond you soon. I'm in vacation for a week without laptop. I checked the patch just before I leaved. 
Dan

Sent from Yahoo Mail on Android 
 
  On Sat, 22 Dec 2018 at 16:07, Jan König<notifications@github.com> wrote:   
Hi Dan, sorry for closing this issue too soon. We had a similar problem in our Slack community where someone reported this to be resolved now.

Which version of Node do you have installed, could you try node -v?

**Comment by jankoenig** [comment] 2018-12-25 16:46
No problem. Happy holidays!

**Comment by pirvulescu** [comment] 2018-12-30 10:46
I'm back :)

```
$ node -v
v6.2.2
```

**Comment by pirvulescu** [comment] 2018-12-30 11:08
It looks like I had a very old version of node. Updated to the last version and it works.
Thanks for the support.

**Comment by jankoenig** [comment] 2018-12-31 10:47
ok great. closing this again

**Closed by jankoenig** 2018-12-31 10:47 UTC
Labels: Bug

**Comment by fredzannarbor** [comment] 2020-02-29 03:15
having this same error now trying to install and run jovo v 3
