### ISSUE TITLE
removeState() failed on GoogleAssistant 

### ISSUE THREAD

**Issue by kouz75** [jovotech/jovo-framework#430] opened 2019-03-22 15:20 UTC
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
On Dialogflow project. this.removeState() don't clear the state.
I need to remove it with : this.$session.$data._JOVO_STATE_=""

## Your Environment

* Jovo Framework version used: 2.1
* Operating System:

**Comment by jankoenig** [comment] 2019-03-22 18:11
Thank you. We'll investigate this early next week

**Comment by aswetlow** [comment] 2019-03-25 15:31
What's the exact version of your Dialogflow plugin? `jovo --version`
We did some changes (two weeks ago?!). It may be fixed already. 

I tested it with the current version and couldn't reproduce it. Could you provide your sample code?

**Comment by kouz75** [comment] 2019-03-25 16:23
Hi,

I have test with the last version without succes.
_JOVO_STATE_ is remove correctly and the context  send to dialogflow is correct.
Jovo debugger don't show any state.  

At the next request, dialogflow send back the  _JOVO_STATE_ at is old value. and the state appear again in the debugger.

The issue appear only on AoG not with Alexa.

I will try to give you a sample soon.

**Comment by kouz75** [comment] 2019-03-25 20:28
Please, find the sample code above.
The probleme appear when  I set a value to undefined in the session and remove the state.

```
app.setHandler({
    LAUNCH() {
        return this.toIntent('HelloWorldIntent');
    },

    HelloWorldIntent() {
        this.$session.$data.lastPlace = "test"
        this.followUpState("testState")
        this.ask('set testState. call intent testState.testIntent');
    },
    'testState':{
        testIntent(){
            this.$session.$data.lastPlace = undefined
            this.removeState()
            this.ask("testState.testIntent")
        }
    },
    testIntent(){
        this.ask("this intent is never call")
    },
    'Default Fallback Intent': function() {
        this.toIntent('Unhandled');
    },
    Unhandled() {
        this.ask("Unhandled")
    }
});
```

**Comment by aswetlow** [comment] 2019-03-28 09:04
Should be fixed now. Could you test it with your setup?

**Comment by kouz75** [comment] 2019-04-01 07:58
It's working fine.

thanks

**Comment by aswetlow** [comment] 2019-04-01 08:03
Perfect!

**Closed by aswetlow** 2019-04-01 08:03 UTC
Labels: help wanted
