### ISSUE TITLE
Problem with ShowImageCard on HelpIntent

### ISSUE THREAD

**Issue by Droppix** [jovotech/jovo-framework#422] opened 2019-03-19 11:02 UTC
Hi,

I don't understand why Card not displayed in the bloc HelpIntent() ?
On others 'Intent' (more complexe with questions -> .ask), it is well displayed!

## Error
```
  HelpIntent() {
        this.showImageCard('Title', 'Content', 'https://www.icone-png.com/png/18/18221.png')                                
            .tell('Bla Bla', 'Bla Bla');    
    },
```

## Log

```
  {
	"request": {
		"type": "IntentRequest",
		"requestId": "...",
		"timestamp": "2019-03-19T10:53:55Z",
		"locale": "...",
		"intent": {
			"name": "HelpIntent",
			"confirmationStatus": "NONE"
		}
	}
}
{
	"version": "1.0",
	"response": {
		"shouldEndSession": true,
		"outputSpeech": {
			"type": "SSML",
			"ssml": "<speak>Bla Bla</speak>"
		},
		"card": {
			"type": "Standard",
			"image": {
				"smallImageUrl": "https://www.icone-png.com/png/18/18221.png",
				"largeImageUrl": "https://www.icone-png.com/png/18/18221.png"
			},
			"title": "Title",
			"text": "Content"
		}
	},
	"sessionAttributes": {}
}
```

## Environment
Jovo version 2.1.2
OS X Mojave

Any idea ?

Thanks

**Comment by jankoenig** [comment] 2019-03-19 11:03
This should throw an error because `tell` only uses one parameter `.tell('Bla Bla', 'Bla Bla');` -> `.tell('Bla Bla')` should work

**Comment by Droppix** [comment] 2019-03-19 11:04
Sorry, but no work!

**Comment by aswetlow** [comment] 2019-03-19 11:16
Hey! I can't reproduce it. 

My test setup: 
```
const app = new App({
intentMap: 'AMAZON.HelpIntent': 'HelpIntent'
});
app.setHandler({
    async LAUNCH() {
        this.ask('How can I help you?')

    },

    HelpIntent()  {
        this.showImageCard('Title', 'Content', 'https://www.icone-png.com/png/18/18221.png')
            .tell('Bla Bla');
    },
}
```
The card appears in the Alexa app.
Sometimes it takes a couple of seconds. Try to restart the app. (Full restart, not just closing and reopening)

**Comment by Droppix** [comment] 2019-03-19 11:50
I try ... but not work.

**Comment by Droppix** [comment] 2019-03-19 11:56
Ok, I don't understand why but now it's works!
I add only 'AMAZON.HelpIntent' : 'HelpIntent' in the config.js (intentMap)

**Comment by jankoenig** [comment] 2019-03-19 14:05
Ah, yes, you can learn more about the intentMap here: https://www.jovo.tech/docs/routing/intents#intentmap

Glad it works now

**Closed by jankoenig** 2019-03-19 14:05 UTC
