### ISSUE TITLE
Google Actio Media Callback not working (edited title)

### ISSUE THREAD

**Issue by RolandOne** [jovotech/jovo-framework#687] opened 2020-03-02 08:50 UTC
## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... In the sample code for the google action media player where it is suppose to loop the action is not looping in mobile https://github.com/jovotech/jovo-framework/blob/master/examples/javascript/02_googleassistant/mediaresponse/src/app.js:

## Expected Behavior
The action should keep looping

## Current Behavior
The action only plays the audio once and says the text before and after the audio

**Comment by aswetlow** [comment] 2020-03-02 14:12
You mean "not working", right? 😄 

I can reproduce on my Pixel 2. But It works on the Simulator and the Google Nest Hub as it should work.

**Comment by RolandOne** [comment] 2020-03-02 14:15
Yeah I meant not working. Updated title.

By reproduce you mean it doesnt loop in your Pixel 2 as well?

**Comment by aswetlow** [comment] 2020-03-02 14:17
Did it work before? (We launched a big update last week)

**Comment by RolandOne** [comment] 2020-03-02 14:51
Yea it would work on mobile the way it would have worked in the simulator.

**Comment by aswetlow** [comment] 2020-03-02 17:51
Hm, the issue exists on jovo-framework v2, too. It looks like a device issue to me.

**Comment by aswetlow** [comment] 2020-03-03 08:49
There are more Mediaresponse issues out there. 

https://github.com/actions-on-google/actions-on-google-nodejs/issues/269
https://github.com/actions-on-google/actions-on-google-nodejs/issues/348

I am afraid that we cannot solve this from the framework side.

**Comment by RolandOne** [comment] 2020-03-03 09:39
Thank you @aswetlow. Should I close this or keep this open till actions-on-google is fixed?

**Comment by aswetlow** [comment] 2020-03-03 11:49
Let's close it now. I will post an update if there is a change.

**Closed by aswetlow** 2020-03-03 11:49 UTC

**Comment by RolandOne** [comment] 2020-03-06 08:23
It's working now. Thanks for your responses on this issue

**Comment by jankoenig** [comment] 2020-03-06 09:57
Great! Thanks for letting us know. Have a great weekend
