### ISSUE TITLE
Facebook messenger 20 second response constraint

### ISSUE THREAD

**Issue by brody-ly** [jovotech/jovo-framework#1133] opened 2021-11-23 05:17 UTC
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Hey Jovo Team,

I've ran into an issue with the `jovo-platform-facebookmessenger` package, where if an intent takes longer than 20 seconds to return a response, Facebook will repeatedly send the same request. This is a [constraint](https://developers.facebook.com/docs/messenger-platform/webhook) that Facebook has imposed on all webhook events.

## Current Behavior

Facebook will repeatedly send the same response to any intents that take longer then 20 seconds to respond.

## Current workaround
For now, I've got a hacky solution that sends a response immediately back to Facebook at the very start of a request. 

```
import { Webhook, ExpressJS } from "jovo-framework";
import { app } from "./app";

// ExpressJS (Jovo Webhook)
const port = process.env.JOVO_PORT || 3000;
Webhook.jovoApp = app;

...

Webhook.post(
  "/webhook",
  async (req: Express.Request, res: Express.Response) => {
    (res as any).status(200).send("ok"); <------- Hacky

    // Let process continue
    await app.handle(new ExpressJS(req, res));
  }
);
```

Is there a better solution than the above? 

## Your Environment

* Jovo Framework version used: 3.5.2
* Operating System: MacOS Catalina. Version: 10.15.4

**Comment by m-ripper** [comment] 2021-11-23 14:17
Hello there, I have had a similar problem in the past. But the main issue for me was not the imposed constraint of Facebook but rather the timeout caused by the Webhook. The default timeout of the webhook is set to 5 seconds. 

My workaround was to pass ` --timeout 20000` to the `run` command. 

I hope this helps.

**Comment by m-ripper** [comment] 2022-01-20 16:47
Closing for now, if this occurs again, feel free to re-open.

**Closed as completed by m-ripper** 2022-01-20 16:47 UTC
