### ISSUE TITLE
Delete Reminder not working

### ISSUE THREAD

**Issue by alvaroNicasource** [jovotech/jovo-framework#1425] opened 2022-09-20 18:39 UTC
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [x] Other... Please describe:

Note: I can get the reminder and Update it but not Delete it.

## Expected Behavior
Delete a reminder

const result = await this.$alexa!.$user.deleteReminder(alertToken);

## Current Behavior

Error.

### Error Log

```
Request to Alexa API failed: Bad Request
 at handleReminderApiErrors (/"path...."/node_modules/@jovotech/platform-alexa/src/api/ReminderApi.ts:225:11)
    at deleteReminder (/"path...."/node_modules/@jovotech/platform-alexa/src/api/ReminderApi.ts:142:5)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at UpdateDeleteReminderComponent.delete ("path...."/src/components/Reminders/UpdateDeleteReminderComponent.ts:217:28)
    at ComponentTreeNode.executeHandler ("path...."/node_modules/@jovotech/framework/src/ComponentTreeNode.ts:87:7)
    at HandlerPlugin.handle ("path...."/node_modules/@jovotech/framework/src/plugins/HandlerPlugin.ts:55:5)
    at Middleware.run ("path...."/node_modules/@jovotech/framework/src/Middleware.ts:24:7)
    at MiddlewareCollection.run ("path...."/node_modules/@jovotech/framework/src/MiddlewareCollection.ts:108:7)
    at App.handle ("path...."/node_modules/@jovotech/framework/src/App.ts:213:7)
    at JovoDebugger.onReceiveRequest ("path...."/node_modules/@jovotech/plugin-debugger/src/JovoDebugger.ts:447:5) {
  code: 'ERROR'
```
```

## Your Environment

<!--- Include as many relevant details about the environment where the bug was discovered -->

- Jovo Framework version used: 4.1.3
- Operating System: OSX 12.6

**Comment by aswetlow** [comment] 2022-09-28 14:18
I can reproduce this error. I think it's an issue on Alexa's side. We call the right API (https://developer.amazon.com/en-US/docs/alexa/smapi/alexa-reminders-api-reference.html#delete-a-reminder) but get a `BAD_REQUEST` response which is not mentioned here: https://developer.amazon.com/en-US/docs/alexa/smapi/alexa-reminders-api-reference.html#delete-a-reminder

One solution (for now): Update the reminder and change the `state` from `ON` to `COMPLETED` (I haven't tested it myself)

**Comment by jankoenig** [comment] 2022-10-06 14:50
Closing this because it doesn't seem like a Jovo issue. Please reopen if it persists.

**Closed as not planned by jankoenig** 2022-10-06 14:50 UTC
