### ISSUE TITLE
Chatbase request error

### ISSUE THREAD

**Issue by davidmatilla17** [jovotech/jovo-framework#740] opened 2020-05-06 07:52 UTC
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
I can see any log on chatbase of any platform.

## Current Behavior
Any time i trigger an intent on alexa or Google Actions is returning me the log i attached  below. I have set all the variables and when the request to the Chatbase API is made they return an error because some field are empty strings or other like user_id is not sent.
Chatbase docs : https://chatbase.com/documentation/generic

My config :
![config](https://user-images.githubusercontent.com/26623859/81149601-cf03b780-8f7e-11ea-9368-08a22cbd3450.png)

### Error log
```
 {"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)",
	"config":{"url":"https://chatbase.com/api/message"
	,"method":"post",
	"data":
		"{"
			api_key":"",
			"intent":"topicQuoteIntent",
			"platform":"Actions",
			"session_id":"projects/nts-ccbot-dea8f/agent/sessions/ABwppHHZRC7NzKplvQSTEEzQ2x7RbeNrWKf3o83t7LwDF_fK6I85lSCzrz4GITxeuLLjy1EFvofReO20Q6v-",
			"time_stamp":1588750061815,
			"type":"user",
			"version":""
		},
	"headers":
		{
			"Accept":"application/json, 
			text/plain,*/*",
			"Content-Type":"application/json",
			"User-Agent":"axios/0.19.2",
			"Content-Length":257},
			"transformRequest":[null],
			"transformResponse":[null],
			"timeout":0,
			"xsrfCookieName":"XSRF-TOKEN",
			"xsrfHeaderName":"X-XSRF-TOKEN",
			"maxContentLength":-1
		}}
```

## Your Environment

    "jovo-analytics-chatbase": "3.0.14",
    "jovo-core": "3.0.14",
    "jovo-framework": "3.0.15",
    "jovo-platform-alexa": "3.0.15",
    "jovo-platform-dialogflow": "3.0.14",
    "jovo-platform-googleassistant": "3.0.15",
    "jovo-plugin-debugger": "3.0.14",
    "request": "2.88.2"

**Comment by KaanKC** [comment] 2020-05-11 08:43
Hey @davidmatilla17,

I couldn't reproduce the error. Could you provide steps on how to reproduce the error?

Besides that, while testing I saw that we used the wrong property name to parse the version in our docs. Please use `appVersion` instead of `version` in your config file.

Btw, it seems like you used two quotes while parsing your API key for Google Assistant.

**Comment by davidmatilla17** [comment] 2020-05-11 12:19
i see that the problem with the api key was my mistake but i have change `version` to `appVersion` and the is showing yet.

![imagen](https://user-images.githubusercontent.com/26623859/81560098-03b5ab80-9391-11ea-8c57-c16c31f70620.png)


i have made some test on postman and i see that the request needed a value for the atribute "user_id":
![imagen](https://user-images.githubusercontent.com/26623859/81560521-d87f8c00-9391-11ea-88f1-3302b4278e05.png)

![imagen](https://user-images.githubusercontent.com/26623859/81560598-095fc100-9392-11ea-953f-f9fdd36f332f.png)

I don't know why is not sending the `user_id`. If it helps the function of the intent is async because i need to load the reponse from an API

**Comment by aswetlow** [comment] 2020-05-11 13:06
The screenshots are really helpful. Could you also provide the request json?

**Comment by KaanKC** [comment] 2020-05-11 13:27
I found the issue with Google. Should be fixed with the next release :+1:

**Closed** 2020-05-11 14:19 UTC

**Comment by aswetlow** [comment] 2020-05-11 14:45
Just published the release. Please update your packages with `jovo update`

**Comment by davidmatilla17** [comment] 2020-05-11 16:21
Okay, Thanks !!

**Comment by davidmatilla17** [comment] 2020-05-12 06:54
Hello, i'm here again @KaanKC ,
I try it on google and goes well but in alexa crashes.
![imagen](https://user-images.githubusercontent.com/26623859/81646905-5db77f00-942c-11ea-91ef-00a9835ea44a.png)

I have reviewed the last commits you have made and I see that the change on the class of ChatbaseGoogleAssistant.ts are not applyed to ChatbaseAlexa.ts

I will put an example:
 - ChatbaseAlexa.ts
![imagen](https://user-images.githubusercontent.com/26623859/81647460-593f9600-942d-11ea-86be-6bf1c6a40886.png)

 - ChatbaseGoogleAssistant.ts
![imagen](https://user-images.githubusercontent.com/26623859/81647666-afacd480-942d-11ea-8b61-057786582281.png)

the `user_id `and the `session_id` are been gotten from diferent places and this made that ChatbaseAlexa.ts crashed.

I hope that help you.

**Comment by KaanKC** [comment] 2020-05-12 09:25
Could you provide the error log as well as both the request and response of the session where the error occurred?

**Comment by davidmatilla17** [comment] 2020-05-13 07:07
error :

![imagen](https://user-images.githubusercontent.com/26623859/81781727-e0a60b80-94f8-11ea-979e-25294d18d35b.png)

the input :

`{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.847a3b92-530d-4286-bc7c-165525aded41",
		"application": {
			"applicationId": "amzn1.ask.skill.784adb28-ba90-44ee-af4a-d24a9abc5703"
		},
		"user": {
			"userId": "amzn1.ask.account.AFO6XSHB6IBVQL6JCBCIJB5FIAHYXXVGMKFXXVLENDJPWG5EJGKP7H4JSMNXFDUGP3BADUQ2E7XFGXCYRJZXOTPRSXDISIJROSNU6RRVGUDEMFGNBPYUAZNHTYVES7HM2WWDBI2ZFMTTHESVDSIQTKRXKTGSTIBNTNUX3BTXRJRQ4ZLKDR3ZKZKCNQYK24HETR7QU4I6KHDFP3I"
		}
	},
	"context": {
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.784adb28-ba90-44ee-af4a-d24a9abc5703"
			},
			"user": {
				"userId": "amzn1.ask.account.AFO6XSHB6IBVQL6JCBCIJB5FIAHYXXVGMKFXXVLENDJPWG5EJGKP7H4JSMNXFDUGP3BADUQ2E7XFGXCYRJZXOTPRSXDISIJROSNU6RRVGUDEMFGNBPYUAZNHTYVES7HM2WWDBI2ZFMTTHESVDSIQTKRXKTGSTIBNTNUX3BTXRJRQ4ZLKDR3ZKZKCNQYK24HETR7QU4I6KHDFP3I"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AHJ6UIZZQKJTU4NWQLFUMH4JBL7RSQGGQDVHGFOUOFOOYX2BCD2DZZMBZPPNIESWMH7FNJN5KSJ66ZI3TRK2VYJXUZCYD6XLJ5WTTI56A4SEBMP37WRYXVCL5Y63TDITFAFYRP6WYMFSXHI57QLERG6OTJVOPWM6YFJL4OUAWHF5EFXBRMMJS",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.eu.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjc4NGFkYjI4LWJhOTAtNDRlZS1hZjRhLWQyNGE5YWJjNTcwMyIsImV4cCI6MTU4OTM1MzcwMywiaWF0IjoxNTg5MzUzNDAzLCJuYmYiOjE1ODkzNTM0MDMsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQVFBbjRCTzBmQ04vMlY0Znk1NEZRaGFaS2dFQUFBQUFBQURiSDVPTlozZlJBKzdLMS9QUDBvUEVMQkhJVGpNWXVFMGNjMXZyLzVJQWJGYWR3SHN0cHVDTmlhb3Vkd2FuNUFSa3c0anhlVkwyWmJOMVdISTlramh6aGQ1SmxtcE9vaVRVOGFtUTF3TWdBOCt1ZGViSXhiOXVTRDJOdGRqVFFhajEvbDJIczlnd3Z0c1pnQm5NOU1hbGxmR3V6eVNWeGlPTWNNWXo5ZTJlTG95ZmhWRUxDbnRWK3J3eGlhSFgremZCdk4rTFhtR0N6OVZLeCtwTkdKNkMrVVZmZ1Fob3NIWVlSeHhSMDlDeGw2WFZYa0k1L2tQOUJFVlExS0FSZ01ZV3pleGw4WnRlTC8wVTFrWTNTSXAvMzlsZytYRFJUc0hBMnNGT3pJNVlaaStmcGRhcStXV1BqeFFJeEtIZDNkb29ueHh5VFlJNzMxY1FKMktxajdPd29NdzZITzNrd2IzTGFSZTVzSXpQUUNoZW02bmVLa1gyb0RrejJ3TE92cWd2QjdpdU1YQTlxKzVNIiwiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUhKNlVJWlpRS0pUVTROV1FMRlVNSDRKQkw3UlNRR0dRRFZIR0ZPVU9GT09ZWDJCQ0QyRFpaTUJaUFBOSUVTV01IN0ZOSk41S1NKNjZaSTNUUksyVllKWFVaQ1lENlhMSjVXVFRJNTZBNFNFQk1QMzdXUllYVkNMNVk2M1RESVRGQUZZUlA2V1lNRlNYSEk1N1FMRVJHNk9USlZPUFdNNllGSkw0T1VBV0hGNUVGWEJSTU1KUyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFGTzZYU0hCNklCVlFMNkpDQkNJSkI1RklBSFlYWFZHTUtGWFhWTEVOREpQV0c1RUpHS1A3SDRKU01OWEZEVUdQM0JBRFVRMkU3WEZHWENZUkpaWE9UUFJTWERJU0lKUk9TTlU2UlJWR1VERU1GR05CUFlVQVpOSFRZVkVTN0hNMldXREJJMlpGTVRUSEVTVkRTSVFUS1JYS1RHU1RJQk5UTlVYM0JUWFJKUlE0WkxLRFIzWktaS0NOUVlLMjRIRVRSN1FVNEk2S0hERlAzSSJ9fQ.i19KxLo0mK_H-CYwFidlhF0XERkldwhOVh51SWrTyFYMPToiyIBxwoxSZfM6zBIY3--H8U0k64ayhbAU6pMXxHWJLxfgvPaVeUiXuRs9QMxBW3PvBgSpbSL2Ts7qdwchMsr-nqvpnTj7Z_ZeuMMA6li4Bj2OG2Ns0I9sMkWKPIhNfGH3oJhZzexz4taETWegJ8n8ExE03L4vwWGKfy-SJp0EnXzLRLX_UX2VAprBdteZQs23h9nqIkuKNulaXG56Rbv3AanBGtSQKzEzvcn6vGrG17d0Gr9N-JP8JR9DJcBCBfoQTN9vwP2TpG7579Tkvhg9ArdFYioSZHNTViWcpg"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 160,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1024,
							"pixelHeight": 600
						}
					}
				}
			}
		]
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.4d35a8c9-76f3-412b-9efa-b472ef4126d2",
		"timestamp": "2020-05-13T07:03:23Z",
		"locale": "es-ES",
		"intent": {
			"name": "topicQuoteIntent",
			"confirmationStatus": "NONE",
			"slots": {
				"topic": {
					"name": "topic",
					"value": "tiempo",
					"confirmationStatus": "NONE",
					"source": "USER"
				}
			}
		}
	}
}`


the output: 

`{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak><prosody  rate=\"100%\" pitch=\"+10%\" volume=\"loud\"><voice name=\"Conchita\">La ocasión, la pintan calva</voice></prosody></speak>"
			},
			"reprompt": {
				"outputSpeech": {
					"type": "SSML",
					"ssml": "<speak><prosody  rate=\"100%\" pitch=\"+10%\" volume=\"loud\"><voice name=\"Conchita\">La ocasión, la pintan calva</voice></prosody></speak>"
				}
			},
			"shouldEndSession": false,
			"type": "_DEFAULT_RESPONSE"
		},
		"sessionAttributes": {}
	}
}`

The response is okay but the problems is that internally jovo framework crashes when is trying to track the user with chatbase.

**Comment by davidmatilla17** [comment] 2020-05-13 07:14
I think that the error is that before the session_id you got it from  `jovo.$request!.toJSON().session.sessionId` and user_id from `jovo.$request!.getUserId()` on ChatbaseGoogleAssistant and you change it to `jovo.$request!.getSessionId()` and `jovo.$user.getId()` respectively but you didn't changed on ChatbaseAlexa.ts.

**Comment by KaanKC** [comment] 2020-05-13 08:54
The error was thrown because we tried to call `replace()` on `undefined`. Should be fixed with the next release.
