### ISSUE TITLE
Initialised new JOVO Project

### ISSUE THREAD

**Issue by santhosh77h** [jovotech/jovo-framework#861] opened 2020-11-18 08:46 UTC
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

from webhook URL on click of launch basic response should have sent. instead received an error on console

## ERROR LOG
``` txt
unhandledRejection
  {}
  Error: Request failed with status code 404
      at createError (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/adapters/http.js:236:11)
      at IncomingMessage.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1183:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  {"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1183:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"http://localhost:3000/webhook","method":"post","data":"{\"version\":\"1.0\",\"session\":{\"new\":true,\"sessionId\":\"amzn1.echo-api.session.0000000-0000-0000-0000-00000000000\",\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"attributes\":{},\"user\":{\"userId\":\"jovo-debugger-user\"}},\"context\":{\"System\":{\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"user\":{\"userId\":\"jovo-debugger-user\"},\"device\":{\"deviceId\":\"amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA\",\"supportedInterfaces\":{\"AudioPlayer\":{},\"Display\":{\"templateVersion\":\"1.0\",\"markupVersion\":\"1.0\"},\"VideoApp\":{},\"Alexa.Presentation.APL\":{\"runtime\":{\"maxVersion\":\"1.0\"}}}}},\"AudioPlayer\":{\"offsetInMilliseconds\":0,\"playerActivity\":\"IDLE\"}},\"request\":{\"type\":\"LaunchRequest\",\"requestId\":\"amzn1.echo-api.request.0000000-0000-0000-0000-00000000000\",\"timestamp\":\"2020-11-18T08:39:29.763Z\",\"locale\":\"en-US\"}}","headers":{"Accept":"application/json","Content-Type":"application/json","jovo-debugger":true,"User-Agent":"axios/0.19.2","Content-Length":1009},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
  Error: Request failed with status code 404
      at createError (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/adapters/http.js:236:11)
      at IncomingMessage.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1183:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  {"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/deviceName/proj/test-assistant/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1183:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"http://localhost:3000/webhook","method":"post","data":"{\"version\":\"1.0\",\"session\":{\"new\":true,\"sessionId\":\"amzn1.echo-api.session.0000000-0000-0000-0000-00000000000\",\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"attributes\":{},\"user\":{\"userId\":\"jovo-debugger-user\"}},\"context\":{\"System\":{\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"user\":{\"userId\":\"jovo-debugger-user\"},\"device\":{\"deviceId\":\"amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA\",\"supportedInterfaces\":{\"AudioPlayer\":{},\"Display\":{\"templateVersion\":\"1.0\",\"markupVersion\":\"1.0\"},\"VideoApp\":{},\"Alexa.Presentation.APL\":{\"runtime\":{\"maxVersion\":\"1.0\"}}}}},\"AudioPlayer\":{\"offsetInMilliseconds\":0,\"playerActivity\":\"IDLE\"}},\"request\":{\"type\":\"LaunchRequest\",\"requestId\":\"amzn1.echo-api.request.0000000-0000-0000-0000-00000000000\",\"timestamp\":\"2020-11-18T08:39:29.763Z\",\"locale\":\"en-US\"}}","headers":{"Accept":"application/json","Content-Type":"application/json","jovo-debugger":true,"User-Agent":"axios/0.19.2","Content-Length":1009},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
```

## Your Environment

  * jovo-core: 3.2.1
  * jovo-db-filedb: 3.2.1
  * jovo-framework: 3.2.1
  * jovo-platform-alexa: 3.2.1
  * jovo-platform-dialogflow: 3.2.1
   * jovo-platform-googleassistant: 3.2.2
  * jovo-plugin-debugger: 3.2.1
  * Operating System: mac os big sur and catalina

**Comment by aswetlow** [comment] 2020-11-19 21:58
Hey @santhosh77h 

Is it still a problem?

Did it happen in an existing project or right after `jovo new`?

**Comment by santhosh77h** [comment] 2020-11-20 02:42
It was happening on existing project..... then created new project same error happened.....

**Comment by santhosh77h** [comment] 2020-11-20 08:24
this error happened 
- when I ran `jovo run` command then
- sending `launch` command from jovo webhook ui.

**Comment by aswetlow** [comment] 2020-11-23 16:47
Can't reproduce :/

Any special logs after running `jovo run`?

**Comment by santhosh77h** [comment] 2020-11-25 15:54
added breakpoint for `uncaughtexception`


error was at http.js inside axios library

value is

```json
{"message":"Request failed with status code 404",
"name":"Error",
"stack":"Error: Request failed with status code 404\n    at createError (/Users/device/employee/lumnify-voice-assistants/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/device/employee/lumnify-voice-assistants/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/device/employee/lumnify-voice-assistants/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1183:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
"config":{
"url":"http://localhost:3000/webhook",
"method":"post",
"data":"{\"version\":\"1.0\",\"session\":{\"new\":true,\"sessionId\":\"amzn1.echo-api.session.0000000-0000-0000-0000-00000000000\",\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"attributes\":{},\"user\":{\"userId\":\"jovo-debugger-user\"}},\"context\":{\"System\":{\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"user\":{\"userId\":\"jovo-debugger-user\"},\"device\":{\"deviceId\":\"amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA\",\"supportedInterfaces\":{\"AudioPlayer\":{},\"Display\":{\"templateVersion\":\"1.0\",\"markupVersion\":\"1.0\"},\"VideoApp\":{},\"Alexa.Presentation.APL\":{\"runtime\":{\"maxVersion\":\"1.0\"}}}}},\"AudioPlayer\":{\"offsetInMilliseconds\":0,\"playerActivity\":\"IDLE\"}},\"request\":{\"type\":\"LaunchRequest\",\"requestId\":\"amzn1.echo-api.request.0000000-0000-0000-0000-00000000000\",\"timestamp\":\"2020-11-25T15:40:21.590Z\",\"locale\":\"en-US\"}}",
"headers":{
"Accept":"application/json",
"Content-Type":"application/json",
"jovo-debugger":true,
"User-Agent":"axios/0.19.2",
"Content-Length":1009
},
"transformRequest":[null],
"transformResponse":[null],
"timeout":0,
"xsrfCookieName":"XSRF-TOKEN",
"xsrfHeaderName":"X-XSRF-TOKEN",
"maxContentLength":-1}}

```


I'm still learning jovo... let me know is there a better approach for debugging...

**Comment by santhosh77h** [comment] 2020-11-25 15:58
this is the value.config

```json
{
  "url": "http://localhost:3000/webhook",
  "method": "post",
  "data": "{\"version\":\"1.0\",\"session\":{\"new\":true,\"sessionId\":\"amzn1.echo-api.session.0000000-0000-0000-0000-00000000000\",\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"attributes\":{},\"user\":{\"userId\":\"jovo-debugger-user\"}},\"context\":{\"System\":{\"application\":{\"applicationId\":\"amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe\"},\"user\":{\"userId\":\"jovo-debugger-user\"},\"device\":{\"deviceId\":\"amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA\",\"supportedInterfaces\":{\"AudioPlayer\":{},\"Display\":{\"templateVersion\":\"1.0\",\"markupVersion\":\"1.0\"},\"VideoApp\":{},\"Alexa.Presentation.APL\":{\"runtime\":{\"maxVersion\":\"1.0\"}}}}},\"AudioPlayer\":{\"offsetInMilliseconds\":0,\"playerActivity\":\"IDLE\"}},\"request\":{\"type\":\"LaunchRequest\",\"requestId\":\"amzn1.echo-api.request.0000000-0000-0000-0000-00000000000\",\"timestamp\":\"2020-11-25T15:40:21.590Z\",\"locale\":\"en-US\"}}",
  "headers": {
    "Accept": "application/json",
    "Content-Type": "application/json",
    "jovo-debugger": true,
    "User-Agent": "axios/0.19.2",
    "Content-Length": 1009
  },
  "transformRequest": [
    null
  ],
  "transformResponse": [
    null
  ],
  "timeout": 0,
  "xsrfCookieName": "XSRF-TOKEN",
  "xsrfHeaderName": "X-XSRF-TOKEN",
  "maxContentLength": -1
}

```

**Comment by santhosh77h** [comment] 2020-11-25 16:05
When I ran the above request from the postman received the correct response as


```js
{
  "version": "1.0",
  "response": {
    "shouldEndSession": false,
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak>Welcome to Rezrv</speak>"
    },
    "reprompt": {
      "outputSpeech": {
        "type": "SSML",
        "ssml": "<speak>Welcome to Rezrv</speak>"
      }
    }
  },
  "sessionAttributes": {}
}

```

I think this an issue with Axios may be not sure yet.....

**Comment by santhosh77h** [comment] 2020-11-25 16:28
Hi @aswetlow, thanks for the help since the jovo internally connecting to port 3000. but in that part, there was a react app running that's why it was throwing an error with 404.... when I stopped that react app and re-run this jovo it's working fine...

is there any possibility that we can add a logger telling that the port is busy.... can't use or use the new port...

**Comment by aswetlow** [comment] 2020-11-30 09:32
I am surprised that the error isn't shown. This is what I get when I run a Jovo app twice.

![image](https://user-images.githubusercontent.com/14978292/100592292-31dfe600-32f7-11eb-8376-68a9882b5578.png)

**Comment by aswetlow** [comment] 2021-04-01 10:36
Closing the issue - Feel free to re-open

**Closed by aswetlow** 2021-04-01 10:36 UTC
