### ISSUE TITLE
Firestore crash when used with Messenger and sessionData field

### ISSUE THREAD

**Issue by Mistic92** [jovotech/jovo-framework#721] opened 2020-04-10 16:18 UTC
## I'm submitting a...

- [ X ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

I'm testing integrations how they are working with FB Messenger and I found out that when I add field [SessionData ](https://www.jovo.tech/docs/data/user#session-data)in config, Firestore can't save this. 

```
	async ON_TEXT() {
		await this.$messengerBot?.showAction(SenderActionType.MarkSeen);
		console.log(this.$cms.responses);
		this.ask(` Echo: ${this.$messengerBot?.getRawText()}`);
	}
```

## Expected Behavior
Just save session data

## Current Behavior
Error 

### Error log
```
  Error -----------------------------------------------------------------

  Message:
  Argument "data" is not a valid Document. Cannot use "undefined" as a Firestore value (found in field userData.session.id).

  Stack:
  Error: Argument "data" is not a valid Document. Cannot use "undefined" as a Firestore value (found in field userData.session.id).
      at Validator.<computed> (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/@google-cloud/firestore/build/src/validate.js:92:27)
      at WriteBatch.set (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/@google-cloud/firestore/build/src/write-batch.js:225:25)
      at DocumentReference.set (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/@google-cloud/firestore/build/src/reference.js:340:27)
      at Firestore.save (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-db-firestore/src/Firestore.ts:154:18)
      at JovoUser.saveDb (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-framework/src/middleware/user/JovoUser.ts:460:35)
      at Middleware.run (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-core/src/core/Middleware.ts:85:20)
      at App.handle (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-core/src/core/BaseApp.ts:277:43)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 0)
      at App.jovo_core_1.BaseApp.handle (/mnt/c/Projects/messenger-tl/hellowrd/node_modules/jovo-platform-facebookmessenger/src/FacebookMessenger.ts:320:9)

   ----------------------------------------------------------------------
```

## Your Environment

* Jovo Framework version used: 3.0.11
* Operating System:

**Comment by jankoenig** [comment] 2020-04-12 09:44
Hi @Mistic92,

Could you share how you're saving session data? Your code example doesn't show it, as far as I understand it there should be a `this.$session.$data...` reference somewhere:

```
async ON_TEXT() {
		await this.$messengerBot?.showAction(SenderActionType.MarkSeen);
		console.log(this.$cms.responses);
		this.ask(` Echo: ${this.$messengerBot?.getRawText()}`);
	}
```

**Comment by Mistic92** [comment] 2020-04-12 11:01
As I was just testing DB options, I have not used reference to session data. But plugin should handle missing data and not crash but maybe just show warning.

**Comment by jankoenig** [comment] 2020-04-12 11:05
Can you show the relevant config?

**Comment by Mistic92** [comment] 2020-08-11 13:03
```js
/** @format */

import { config } from 'jovo-framework';
import './credentials.json';

process.env.JOVO_LOG_LEVEL = 'DEBUG';

export = config({
  logging: {
    request: true,
    requestObjects: ['request', 'context.System.user'],
    response: true,
    responseObjects: ['response'],
  },

  intentMap: {
    'AMAZON.StopIntent': 'END',
  },
  credentialsFile: require('./credentials.json'),
  db: {
    FileDb: {
      pathToFile: '../db/db.json',
    },
    Firestore: {
      credential: require('./credentials.json'),
      databaseURL: 'https://xxxxxxxxxxxxxxx.firebaseio.com',
      collectionName: 'jovo',
    },
  },
  plugin: {
    JovoClassHandler: {
      // handlers: [FaqHandler],
      handlers: [__dirname + '/**/*.handler.{ts,js}'],
    },
  },
  analytics: {
    // Configuration for generic tracking plugin
    GoogleAnalytics: {
      trackingId: 'xxxxxxxxxx',
      trackDirectives: true,
    },
  },
  platform: {
    FacebookMessenger: {
      pageAccessToken:
        'xxxxxxxxxxxxxxxx',
      verifyToken: 'xxxxxxxxxxx',
      launch: {
        updateOnSetup: true,
        data: 'someLaunchPayload',
      },
    },
  },
  i18n: {
    debug: true,
    fallbackLng: 'en-US',
    resources: {
      'en-US': require('./i18n/en-US.json'),
    },
  },
  user: {
    updatedAt: true,
    dataCaching: false,
    implicitSave: true,
    metaData: {
      enabled: true,
      lastUsedAt: true,
      sessionsCount: true,
      createdAt: true,
      requestHistorySize: 4,
      devices: true,
    },
    sessionData: {
      enabled: true,
      data: false,
      id: true,
    },
    context: {
      enabled: true,
      prev: {
        size: 3,
        request: {
          intent: true,
          state: true,
          inputs: true,
          timestamp: true,
        },
        response: {
          speech: true,
          reprompt: true,
          state: true,
          output: false,
        },
      },
    },
  },
});

```

**Comment by m-ripper** [comment] 2020-09-22 15:21
This seems to be a duplicate of #776.
I've written down an answer there.

**Closed** 2020-10-16 14:01 UTC
